CC=gcc
COMMON= -Wall -Wextra -Wfloat-equal -Wvla -Wpedantic -std=c99 -Werror
DEBUG= -g3
SANITIZE= $(COMMON) -fsanitize=undefined -fsanitize=address $(DEBUG)
VALGRIND= $(COMMON) $(DEBUG)
PRODUCTION= $(COMMON) -O3
LDLIBS =

all: testrealloc

t : boolarr.h Realloc/specific.h Realloc/realloc.c testboolarr.c General/general.h General/general.c
	$(CC) testboolarr.c Realloc/realloc.c General/general.c -o testrealloc -I./Realloc -IGeneral $(PRODUCTION) $(LDLIBS)

# testrealloc_s : boolarr.h Realloc/specific.h Realloc/realloc.c testboolarr.c General/general.h General/general.c
# 	$(CC) testboolarr.c Realloc/realloc.c General/general.c -o testrealloc_s -I./Realloc -IGeneral $(SANITIZE) $(LDLIBS)

# testrealloc_v : boolarr.h Realloc/specific.h Realloc/realloc.c testboolarr.c General/general.h General/general.c
# 	$(CC) testboolarr.c Realloc/realloc.c General/general.c -o testrealloc_v -I./Realloc -IGeneral $(VALGRIND) $(LDLIBS)


# clean:
# 	rm -f testrealloc_s testrealloc_v testrealloc

# run: all
# 	./testrealloc_s
# 	valgrind ./testrealloc_v